--- name:kuka

# Planner Properties.
config:
  planner_config:
    kinematics_config:
      kinematic_solver: :KDL
      base_name: 'base_link'
      tip_name: 'link_7'
      urdf_file: "./data/kuka_iiwa.urdf"
      solver_config_abs_path: "./config"
      solver_config_filename: "kdl_config.yml"
    robot_model_config:
      urdf_file: "./data/kuka_iiwa.urdf"
      srdf_file: "./data/kuka_iiwa.srdf"
      planning_group_name: manipulator
    #planner_specific_config: "./config/stomp.yml"
    #planner: :STOMP
    planner_specific_config: "./config/ompl.yml"
    planner: :OMPL 
  env_config:
    collision_detection_config: 
      collision_library: :FCL
      collision_info_type: :DISTANCE
      max_num_collision_contacts: 1

