--- name:kuka
# The limits for the joints
limits:
  names:
  - joint_a1
  - joint_a2
  - joint_a3
  - joint_a4
  - joint_a5
  - joint_a6
  - joint_a7
  elements:
  - min:
      position: -2.9668
      speed: -1
      effort: -3.0
    max:
      position: 2.9668
      speed: 1
      effort: 3.0
  - min:
      position: -2.0942
      speed: -1
      effort: -3.0
    max:
      position: 2.0942
      speed: 1
      effort: 3.0
  - min:
      position: -2.9668
      speed: -1
      effort: -3.0
    max:
      position: 2.9668
      speed: 1
      effort: 3.0
  - min:
      position: -2.0942
      speed: -1
      effort: -3.0
    max:
      position: 2.0942
      speed: 1
      effort: 3.0
  - min:
      position: -2.9668
      speed: -1
      effort: -3.0
    max:
      position: 2.9668
      speed: 1
      effort: 3.0
  - min:
      position: -2.0942
      speed: -1
      effort: -3.0
    max:
      position: 2.0942
      speed: 1
      effort: 3.0
  - min:
      position: -3.14159
      speed: -1
      effort: -3.0
    max:
      position: 3.14159
      speed: 1
      effort: 3.0

# no documentation available for this property
noise_mean:
  position: 0
  speed: 0
  effort: 0
  raw: 0
# no documentation available for this property
noise_variance:
  position: 0
  speed: 0
  effort: 0
  raw: 0
# In seconds
simulation_step_time: 0.0
# no documentation available for this property
use_fixed_simulation_step_time: false

